const CLASSES = ['fill-base', 'fill-1', 'fill-2', 'fill-3', 'ink-base', 'ink-1', 'ink-2', 'ink-3', 'mark-1', 'mark-2', 'mark-3'];
const CLASS_RENAMES = {'main-fill':'fill-base', 'main-ink':'ink-base', 'dots-1':'mark-1', 'dots-2':'mark-2', 'dots-3':'mark-3'};
const canvas = document.querySelector('#canvas');
const partList = document.querySelector('#part-list');
const markerList = document.querySelector('#marker-list');
const selectedParts = new Set();
const STORAGE_KEY = 'ayah-marker-annotations-v1';
const blankAnnotations = () => ({ version: 1, componentIdFormat: 'path-{pathIndex}-contour-{contourIndex}', markers: {} });
const annotations = (() => { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)) || blankAnnotations(); Object.values(saved.markers || {}).forEach(entry => ['parts','interiorFills'].forEach(bucket => { const data = entry[bucket] || {}; Object.entries(CLASS_RENAMES).forEach(([oldName,newName]) => { if (data[oldName]) { data[newName] = [...(data[newName] || []), ...data[oldName]]; delete data[oldName]; } }); entry[bucket] = data; })); return saved; } catch { return blankAnnotations(); } })();
let markers = [], markerChoices = [], markerIndex = 0, currentParts = [], currentViewBox = '';

function splitContours(path) { return path.match(/M[^M]*/g) || []; }
function currentMarker() { return markerChoices[markerIndex]; }
function designGroup(marker) { return marker.id.split('-')[0]; }
function hasAssignment(entry) { return entry && ['parts', 'interiorFills'].some(bucket => Object.values(entry[bucket] || {}).some(values => values.length)); }
function normalizeAnnotation(entry) { entry.parts ||= {}; entry.interiorFills ||= {}; CLASSES.forEach(name => { entry.parts[name] ||= []; entry.interiorFills[name] ||= []; }); return entry; }
function annotationForMarker() { const id = currentMarker().id; if (!annotations.markers[id]) { const sibling = markers.find(marker => designGroup(marker) === designGroup(currentMarker()) && hasAssignment(annotations.markers[marker.id])); annotations.markers[id] = sibling ? structuredClone(annotations.markers[sibling.id]) : {}; } return normalizeAnnotation(annotations.markers[id]); }
function syncFamilyAnnotations() { const source = structuredClone(annotationForMarker()); markers.filter(marker => designGroup(marker) === designGroup(currentMarker())).forEach(marker => { annotations.markers[marker.id] = structuredClone(source); }); }
function classesForMarker() { return annotationForMarker().parts; }
function assignmentOf(partId) { return CLASSES.find(name => classesForMarker()[name].includes(partId)); }
function saveAnnotations() { localStorage.setItem(STORAGE_KEY, JSON.stringify(annotations)); renderMarkerJson(); }
function renderMarkerJson() { document.querySelector('#marker-json').textContent = JSON.stringify({ marker: currentMarker().id, ...annotationForMarker() }, null, 2); }
function updateProgress() { document.querySelector('#progress').textContent = `${markerIndex + 1} of ${markerChoices.length} designs · ${Object.keys(annotations.markers).length} weights annotated`; }
function togglePart(partId) { selectedParts.has(partId) ? selectedParts.delete(partId) : selectedParts.add(partId); updateSelection(); }
function updateSelection() { document.querySelectorAll('[data-part-id]').forEach(element => element.classList.toggle('selected', selectedParts.has(element.dataset.partId))); document.querySelector('#hint').textContent = selectedParts.size ? `${selectedParts.size} part${selectedParts.size === 1 ? '' : 's'} selected` : 'Click visible parts to select multiple pieces.'; }
function renderPartList() { partList.innerHTML = ''; currentParts.forEach(part => { const chip = document.createElement('button'); chip.className = 'part-chip'; chip.dataset.partId = part.id; chip.textContent = `${part.id}${assignmentOf(part.id) ? ` · ${assignmentOf(part.id)}` : ''}`; chip.onclick = () => togglePart(part.id); partList.append(chip); }); }
function renderMarkerList() { markerList.innerHTML = ''; markerChoices.forEach((marker, index) => { const button = document.createElement('button'); button.className = 'marker-button'; button.dataset.group = designGroup(marker); button.setAttribute('aria-current', index === markerIndex); button.innerHTML = `<img class="marker-thumb" src="../${marker.file}" alt=""><span>${designGroup(marker)}</span>`; button.title = `${marker.id} represents every available weight`; button.onclick = () => { markerIndex = index; renderEditor(); }; markerList.append(button); }); }
function buildOverlay(raw) { const documentSvg = new DOMParser().parseFromString(raw, 'image/svg+xml').documentElement; const overlay = documentSvg.cloneNode(false); overlay.classList.add('marker-overlay'); let pathIndex = 0; documentSvg.querySelectorAll('path').forEach(path => { splitContours(path.getAttribute('d')).forEach((contour, contourIndex) => { const id = `path-${pathIndex}-contour-${contourIndex}`; const element = document.createElementNS('http://www.w3.org/2000/svg', 'path'); element.setAttribute('d', contour); element.dataset.partId = id; element.addEventListener('click', event => { event.stopPropagation(); togglePart(id); }); overlay.append(element); currentParts.push({id, d: contour, closed: /[zZ]\s*$/.test(contour)}); }); pathIndex++; }); return overlay; }
function buildFillPreview() { const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); svg.classList.add('marker-fill-preview'); svg.setAttribute('viewBox', currentViewBox); const byId = new Map(currentParts.map(part => [part.id, part])); Object.values(annotationForMarker().interiorFills).flat().forEach(id => { const part = byId.get(id); if (!part) return; const path = document.createElementNS('http://www.w3.org/2000/svg', 'path'); path.setAttribute('d', part.d); path.setAttribute('fill', '#df3c3c'); path.setAttribute('opacity', '.78'); svg.append(path); }); return svg; }
function refreshFillPreview() { canvas.querySelector('.marker-fill-preview')?.replaceWith(buildFillPreview()); }
async function renderEditor() { selectedParts.clear(); currentParts = []; const marker = currentMarker(); const raw = await fetch(`../${marker.file}`).then(response => response.text()); const base = new DOMParser().parseFromString(raw, 'image/svg+xml').documentElement; base.classList.add('marker-base'); currentViewBox = base.getAttribute('viewBox'); const overlay = buildOverlay(raw); canvas.replaceChildren(buildFillPreview(), base, overlay); document.querySelector('#marker-name').textContent = marker.id; renderPartList(); renderMarkerList(); updateProgress(); updateSelection(); renderMarkerJson(); }
function assignSelected(className) { const classes = classesForMarker(); CLASSES.forEach(name => classes[name] = classes[name].filter(id => !selectedParts.has(id))); classes[className].push(...selectedParts); syncFamilyAnnotations(); selectedParts.clear(); renderPartList(); updateSelection(); updateProgress(); saveAnnotations(); }
function emptyMarkerAnnotation() { return { parts: Object.fromEntries(CLASSES.map(name => [name, []])), interiorFills: Object.fromEntries(CLASSES.map(name => [name, []])) }; }
function exportJson() { const complete = { ...annotations, markers: Object.fromEntries(markers.map(marker => [marker.id, structuredClone(annotations.markers[marker.id] || emptyMarkerAnnotation())])) }; return JSON.stringify(complete, null, 2); }
fetch('../collection.json').then(response => response.json()).then(data => { markers = data.markers; markerChoices = markers.filter((marker, index) => markers.findIndex(candidate => designGroup(candidate) === designGroup(marker)) === index); renderEditor(); });
document.querySelector('#assign').onclick = () => assignSelected(document.querySelector('#part-class').value);
document.querySelector('#inside-fill').onclick = () => { const fillClass = document.querySelector('#part-class').value; const closed = currentParts.filter(part => selectedParts.has(part.id) && part.closed).map(part => part.id); if (!closed.length) { document.querySelector('#saved').textContent = 'Select at least one closed contour to create an interior fill.'; return; } const fills = annotationForMarker().interiorFills[fillClass]; fills.push(...closed.filter(id => !fills.includes(id))); syncFamilyAnnotations(); refreshFillPreview(); saveAnnotations(); document.querySelector('#saved').textContent = `Added ${closed.length} red interior fill contour${closed.length === 1 ? '' : 's'} to ${fillClass}.`; };
document.querySelector('#clear').onclick = () => { const classes = classesForMarker(); CLASSES.forEach(name => classes[name] = classes[name].filter(id => !selectedParts.has(id))); CLASSES.forEach(name => annotationForMarker().interiorFills[name] = annotationForMarker().interiorFills[name].filter(id => !selectedParts.has(id))); syncFamilyAnnotations(); selectedParts.clear(); renderPartList(); updateSelection(); saveAnnotations(); };
document.querySelector('#previous').onclick = () => { markerIndex = (markerIndex + markerChoices.length - 1) % markerChoices.length; renderEditor(); };
document.querySelector('#next').onclick = () => { markerIndex = (markerIndex + 1) % markerChoices.length; renderEditor(); };
document.querySelector('#download').onclick = () => { const url = URL.createObjectURL(new Blob([exportJson()], {type:'application/json'})); const link = Object.assign(document.createElement('a'), {href:url, download:'ayah-marker-annotations.json'}); link.click(); URL.revokeObjectURL(url); };
document.querySelector('#copy').onclick = async () => { await navigator.clipboard.writeText(exportJson()); document.querySelector('#saved').textContent = 'Annotations copied.'; };
