const parts = ['fill-base','fill-1','fill-2','fill-3','ink-base','ink-1','ink-2','ink-3','mark-1','mark-2','mark-3'];
const renderOrder = ['ink-base','ink-1','ink-2','ink-3','fill-base','fill-1','fill-2','fill-3','mark-1','mark-2','mark-3'];
const colors = document.querySelector('#colors'), canvas = document.querySelector('#canvas'), status = document.querySelector('#status');
let records = [], svgCache = [], selectedIndex = 0, annotations = {markers:{}};
const defaultTheme = Object.fromEntries(parts.map(part => [part, getComputedStyle(document.documentElement).getPropertyValue(`--${part}`).trim()]));
function theme() { return Object.fromEntries(parts.map(part => [part, getComputedStyle(document.documentElement).getPropertyValue(`--${part}`).trim()])); }
function setColor(part, value) { document.documentElement.style.setProperty(`--${part}`, value); }
function splitContours(path) { return path.match(/M[^M]*/g) || []; }
function hasAssignments(annotation) { return annotation && ['parts', 'interiorFills', 'generatedFills'].some(bucket => Object.values(annotation[bucket] || {}).some(values => values.length)); }
function localAnnotations() { try { return JSON.parse(localStorage.getItem('ayah-marker-annotations-v1')) || {markers:{}}; } catch { return {markers:{}}; } }
function mergedAnnotations(fileAnnotations) { const local = localAnnotations(); const ids = new Set([...Object.keys(fileAnnotations.markers || {}), ...Object.keys(local.markers || {})]); const markers = Object.fromEntries([...ids].map(id => { const fileMarker = fileAnnotations.markers?.[id] || {}; const localMarker = local.markers?.[id] || {}; return [id, {...fileMarker, ...localMarker, parts: {...(fileMarker.parts || {}), ...(localMarker.parts || {})}, interiorFills: {...(fileMarker.interiorFills || {}), ...(localMarker.interiorFills || {})}, generatedFills: {...(fileMarker.generatedFills || {}), ...(localMarker.generatedFills || {})}}]; })); return {...fileAnnotations, markers}; }
function familyAnnotation(record) { const own = annotations.markers[record.id]; if (hasAssignments(own)) return own; const family = record.id.split('-')[0]; return Object.entries(annotations.markers).find(([id, annotation]) => id.split('-')[0] === family && hasAssignments(annotation))?.[1] || own; }
function layerStyle(part) { return `fill:var(--${part},currentColor)`; }
function availableParts(record) { const annotation = familyAnnotation(record); const assigned = annotation ? ['parts', 'interiorFills', 'generatedFills'].flatMap(bucket => Object.entries(annotation[bucket] || {}).filter(([, values]) => values.length).map(([part]) => part)) : []; return [...new Set(assigned.length ? assigned : parts.filter(part => record.parts?.[part]))]; }
function renderColorControls(record) { colors.replaceChildren(); availableParts(record).forEach(part => { const label = document.createElement('label'); label.className = 'color'; label.textContent = part; const input = document.createElement('input'); input.type = 'color'; input.value = theme()[part]; input.oninput = () => setColor(part,input.value); label.append(input); colors.append(label); }); }
function markerCss(record) { const variables = availableParts(record).map(part => `  --${part}: ${theme()[part]};`).join('\n'); return `/* ${record.id} */\n.ayah-marker {\n${variables}\n}`; }
function filterGallery() { const query = document.querySelector('#search').value.trim().toLowerCase(); const cards = [...document.querySelectorAll('.marker-card')]; let visible = 0; cards.forEach(card => { const matches = card.dataset.marker.includes(query); card.hidden = !matches; if (matches) visible++; }); document.querySelector('#gallery-count').textContent = `${visible} of ${records.length} markers`; }
function annotatedSvg(raw, annotation) { const source = new DOMParser().parseFromString(raw, 'image/svg+xml').documentElement; const documentSvg = document.implementation.createDocument('http://www.w3.org/2000/svg', 'svg', null); const svg = documentSvg.documentElement; svg.setAttribute('viewBox', source.getAttribute('viewBox')); svg.setAttribute('class', 'ayah-marker'); const contours = new Map(); let pathIndex = 0; source.querySelectorAll('path').forEach(path => { splitContours(path.getAttribute('d')).forEach((contour, contourIndex) => contours.set(`path-${pathIndex}-contour-${contourIndex}`, contour)); pathIndex++; }); const addGroup = (part, generated = false) => { const group = documentSvg.createElementNS(svg.namespaceURI, 'g'); group.setAttribute('data-part', part); group.setAttribute('fill-rule', 'evenodd'); group.setAttribute('style', layerStyle(part)); if (generated) group.setAttribute('data-generated-fill', 'true'); svg.append(group); return group; }; const generatedGroups = Object.fromEntries(parts.map(part => [part, addGroup(part, true)])); const appendShape = (part, shape) => { if (!generatedGroups[part] || !shape?.type) return; const element = documentSvg.createElementNS(svg.namespaceURI, shape.type); Object.entries(shape).forEach(([name, value]) => { if (name !== 'type') element.setAttribute(name, value); }); generatedGroups[part].append(element); }; Object.entries(annotation.generatedFills || {}).forEach(([part, shapes]) => shapes.forEach(shape => appendShape(part, shape))); Object.entries(annotation.interiorFills || {}).forEach(([part, ids]) => ids.forEach(id => { const contour = contours.get(id); if (!contour) return; const output = documentSvg.createElementNS(svg.namespaceURI, 'path'); output.setAttribute('d', contour); generatedGroups[part].append(output); })); const groups = Object.fromEntries(renderOrder.map(part => [part, addGroup(part)])); const assignments = new Map(); Object.entries(annotation.parts).forEach(([part, ids]) => ids.forEach(id => assignments.set(id, part))); contours.forEach((contour, id) => { const part = assignments.get(id) || 'ink-base', output = documentSvg.createElementNS(svg.namespaceURI, 'path'); output.setAttribute('d', contour); groups[part].append(output); }); return new XMLSerializer().serializeToString(svg); }
async function render() { const record = records[selectedIndex]; canvas.innerHTML = svgCache[selectedIndex]; renderColorControls(record); status.textContent = `${record.id} · ${availableParts(record).join(', ') || 'No assigned classes'}`; document.querySelectorAll('.marker-card').forEach(card => card.setAttribute('aria-pressed', +card.dataset.index === selectedIndex)); }
Promise.all([fetch('../assets/standardized/manifest.json?v=collection-47-1').then(r => r.json()), fetch('../collection.json?v=collection-47-1').then(r => r.json()), fetch('../annotations.json?v=collection-47-1').then(r => r.json())]).then(async ([standardized, collection, fileAnnotations]) => { annotations = mergedAnnotations(fileAnnotations); records = standardized.markers; document.querySelector('#marker-count').textContent = `${records.length} markers`; const originals = new Map(collection.markers.map(marker => [marker.id, marker.file])); svgCache = await Promise.all(records.map(async record => { const annotation = familyAnnotation(record); if (hasAssignments(annotation)) return annotatedSvg(await fetch(`../${originals.get(record.id)}?v=source-safe-1`).then(r => r.text()), annotation); return fetch(`../${record.file}?v=source-safe-1`).then(r => r.text()); })); const gallery = document.querySelector('#gallery'); records.forEach((record,index) => { const button = document.createElement('button'); button.className = 'marker-card'; button.dataset.index = index; button.dataset.marker = record.id.toLowerCase(); button.setAttribute('aria-pressed', 'false'); button.innerHTML = `${svgCache[index]}<small>${record.id}</small>`; button.onclick = () => { selectedIndex = index; render(); window.scrollTo({top: 0, behavior: 'smooth'}); }; gallery.append(button); }); filterGallery(); render(); });
document.querySelector('#copy').onclick = async () => { const record = records[selectedIndex]; await navigator.clipboard.writeText(markerCss(record)); document.querySelector('#copy').textContent='Copied'; setTimeout(()=>document.querySelector('#copy').textContent='Copy CSS',1200); };
document.querySelector('#reset').onclick = () => { Object.entries(defaultTheme).forEach(([part, value]) => setColor(part, value)); renderColorControls(records[selectedIndex]); };
document.querySelector('#search').oninput = filterGallery;
