const parts = ['fill-base','fill-1','fill-2','fill-3','ink-base','ink-1','ink-2','ink-3','mark-1','mark-2','mark-3'];
const renderOrder = ['fill-base','fill-1','fill-2','fill-3','ink-base','ink-1','ink-2','ink-3','mark-1','mark-2','mark-3'];
const colors = document.querySelector('#colors'), canvas = document.querySelector('#canvas'), status = document.querySelector('#status');
let records = [], svgCache = [], selectedIndex = 0, annotations = {markers:{}};
const defaultTheme = Object.fromEntries(parts.map(part => [part, getComputedStyle(document.documentElement).getPropertyValue(`--${part}`).trim()]));
function theme() { return Object.fromEntries(parts.map(part => [part, getComputedStyle(document.documentElement).getPropertyValue(`--${part}`).trim()])); }
function setColor(part, value) { document.documentElement.style.setProperty(`--${part}`, value); }
function splitContours(path) { return path.match(/M[^M]*/g) || []; }
const measureSvg = (() => { const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); svg.setAttribute('style', 'position:absolute;width:0;height:0;overflow:hidden'); document.body.append(svg); return svg; })();
function measured(contour) { const path = document.createElementNS('http://www.w3.org/2000/svg', 'path'); path.setAttribute('d', contour); path.setAttribute('fill-rule', 'evenodd'); measureSvg.append(path); return path; }
function interiorPoint(path) { const box = path.getBBox(); for (let row = 1; row < 8; row++) for (let column = 1; column < 8; column++) { const point = {x: box.x + box.width * column / 8, y: box.y + box.height * row / 8}; if (path.isPointInFill(point)) return point; } return {x: box.x + box.width / 2, y: box.y + box.height / 2}; }
function hasAssignments(annotation) { return annotation && ['parts', 'interiorFills', 'generatedFills'].some(bucket => Object.values(annotation[bucket] || {}).some(values => values.length)); }
function localAnnotations() { try { return JSON.parse(localStorage.getItem('ayah-marker-annotations-v1')) || {markers:{}}; } catch { return {markers:{}}; } }
function mergedAnnotations(fileAnnotations) { const local = localAnnotations(); const ids = new Set([...Object.keys(fileAnnotations.markers || {}), ...Object.keys(local.markers || {})]); const markers = Object.fromEntries([...ids].map(id => { const fileMarker = fileAnnotations.markers?.[id] || {}; const localMarker = local.markers?.[id] || {}; return [id, {...fileMarker, ...localMarker, parts: {...(fileMarker.parts || {}), ...(localMarker.parts || {})}, interiorFills: {...(fileMarker.interiorFills || {}), ...(localMarker.interiorFills || {})}, generatedFills: {...(fileMarker.generatedFills || {}), ...(localMarker.generatedFills || {})}}]; })); return {...fileAnnotations, markers}; }
function familyAnnotation(record) { const own = annotations.markers[record.id]; if (hasAssignments(own)) return own; const family = record.id.split('-')[0]; return Object.entries(annotations.markers).find(([id, annotation]) => id.split('-')[0] === family && hasAssignments(annotation))?.[1] || own; }
function layerStyle(part) { return `fill:var(--${part},currentColor)`; }
function availableParts(record) { const annotation = familyAnnotation(record); const assigned = annotation ? ['parts', 'interiorFills', 'generatedFills'].flatMap(bucket => Object.entries(annotation[bucket] || {}).filter(([, values]) => values.length).map(([part]) => part)) : []; return [...new Set(assigned.length ? assigned : parts.filter(part => record.parts?.[part]))]; }
function renderColorControls(record) { colors.replaceChildren(); availableParts(record).forEach(part => { const label = document.createElement('label'); label.className = 'color'; label.textContent = part; const input = document.createElement('input'); input.type = 'color'; input.value = theme()[part]; input.oninput = () => setColor(part,input.value); label.append(input); colors.append(label); }); }
function markerCss(record) { const variables = availableParts(record).map(part => `  --${part}: ${theme()[part]};`).join('\n'); return `/* ${record.id} */\n.ayah-marker {\n${variables}\n}`; }
function filterGallery() { const query = document.querySelector('#search').value.trim().toLowerCase(); const cards = [...document.querySelectorAll('.marker-card')]; let visible = 0; cards.forEach(card => { const matches = card.dataset.marker.includes(query); card.hidden = !matches; if (matches) visible++; }); document.querySelector('#gallery-count').textContent = `${visible} of ${records.length} markers`; }
function annotatedSvg(raw, annotation) { const source = new DOMParser().parseFromString(raw, 'image/svg+xml').documentElement; const documentSvg = document.implementation.createDocument('http://www.w3.org/2000/svg', 'svg', null); const svg = documentSvg.documentElement; svg.setAttribute('viewBox', source.getAttribute('viewBox')); svg.setAttribute('class', 'ayah-marker'); const contours = new Map(); let pathIndex = 0; source.querySelectorAll('path').forEach(path => { splitContours(path.getAttribute('d')).forEach((contour, contourIndex) => contours.set(`path-${pathIndex}-contour-${contourIndex}`, contour)); pathIndex++; }); const addGroup = (part, generated = false) => { const group = documentSvg.createElementNS(svg.namespaceURI, 'g'); group.setAttribute('data-part', part); group.setAttribute('fill-rule', 'evenodd'); group.setAttribute('style', layerStyle(part)); if (generated) group.setAttribute('data-generated-fill', 'true'); svg.append(group); return group; }; const generatedGroups = Object.fromEntries(parts.map(part => [part, addGroup(part, true)])); const appendShape = (part, shape) => { if (!generatedGroups[part] || !shape?.type) return; const element = documentSvg.createElementNS(svg.namespaceURI, shape.type); Object.entries(shape).forEach(([name, value]) => { if (name !== 'type') element.setAttribute(name, value); }); generatedGroups[part].append(element); }; Object.entries(annotation.generatedFills || {}).forEach(([part, shapes]) => shapes.forEach(shape => appendShape(part, shape))); Object.entries(annotation.interiorFills || {}).forEach(([part, ids]) => ids.forEach(id => { const contour = contours.get(id); if (!contour) return; const output = documentSvg.createElementNS(svg.namespaceURI, 'path'); output.setAttribute('d', contour); generatedGroups[part].append(output); })); const groups = Object.fromEntries(renderOrder.map(part => [part, addGroup(part)])); const assignments = new Map(); Object.entries(annotation.parts).forEach(([part, ids]) => ids.forEach(id => assignments.set(id, part))); const placements = []; contours.forEach((contour, id) => { const part = assignments.get(id) || 'ink-base', path = measured(contour); placements.push({part, contour, path, point: interiorPoint(path)}); }); renderOrder.forEach(part => { const own = placements.filter(placement => placement.part === part); if (!own.length) return; const contained = placements.filter(other => other.part !== part && renderOrder.indexOf(other.part) < renderOrder.indexOf(part) && own.some(placement => placement.path.isPointInFill(other.point))); const holes = contained.filter(other => !contained.some(outer => outer !== other && outer.path.isPointInFill(other.point))); const output = documentSvg.createElementNS(svg.namespaceURI, 'path'); output.setAttribute('d', [...own, ...holes].map(placement => placement.contour).join(' ')); groups[part].append(output); }); placements.forEach(placement => placement.path.remove()); return new XMLSerializer().serializeToString(svg); }
const weightOrder = ['thin','extralight','light','regular','medium','semibold','bold','extrabold','black','regular-bold','regular-black'];
function weightRank(weight) { const rank = weightOrder.indexOf(weight); return rank < 0 ? weightOrder.length : rank; }
const weightNames = {thin:'Thin', extralight:'ExtraLight', light:'Light', regular:'Regular', medium:'Medium', semibold:'SemiBold', bold:'Bold', extrabold:'ExtraBold', black:'Black'};
function weightLabel(weight) { return weight.split('-').map(word => weightNames[word] || word).join(' '); }
function buildFamilies() { const grouped = new Map(); records.forEach((record, index) => { const key = record.id.split('-')[0]; if (!grouped.has(key)) grouped.set(key, {key, variants: []}); grouped.get(key).variants.push({index, record, weight: record.id.slice(key.length + 1)}); }); const families = [...grouped.values()].sort((a, b) => a.key.localeCompare(b.key)); families.forEach(family => { family.variants.sort((a, b) => weightRank(a.weight) - weightRank(b.weight)); family.cover = family.variants.find(variant => variant.weight === 'regular') || family.variants[Math.floor(family.variants.length / 2)]; }); return families; }
function currentFamily() { return families[selectedFamily]; }
function currentVariant() { return currentFamily().variants[selectedVariant]; }
function renderWeights() { const family = currentFamily(); weights.replaceChildren(); weights.hidden = family.variants.length < 2; family.variants.forEach((variant, index) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'weight'; button.textContent = weightLabel(variant.weight); button.setAttribute('aria-pressed', index === selectedVariant); button.onclick = () => { selectedVariant = index; render(); }; weights.append(button); }); }
function filterGallery() { const query = document.querySelector('#search').value.trim().toLowerCase(); let visible = 0; document.querySelectorAll('.marker-card').forEach(card => { const matches = card.dataset.search.includes(query); card.hidden = !matches; if (matches) visible++; }); document.querySelector('#gallery-count').textContent = `${visible} of ${families.length} designs · ${records.length} weights total`; }
function select(familyIndex, variantIndex = 0) { selectedFamily = familyIndex; selectedVariant = variantIndex; render(); }
function render() { const family = currentFamily(), variant = currentVariant(); canvas.innerHTML = svgCache[variant.index]; renderWeights(); renderColorControls(variant.record); const layers = availableParts(variant.record); status.textContent = `${variant.record.id} · ${layers.length ? layers.join(', ') : 'no assigned layers'}`; document.querySelectorAll('.marker-card').forEach(card => card.setAttribute('aria-pressed', +card.dataset.family === selectedFamily)); }
const weights = document.querySelector('#weights');
let families = [], selectedFamily = 0, selectedVariant = 0;
Promise.all([fetch('../assets/standardized/manifest.json?v=collection-47-1').then(r => r.json()), fetch('../collection.json?v=collection-47-1').then(r => r.json()), fetch('../annotations.json?v=collection-47-1').then(r => r.json())]).then(async ([standardized, collection, fileAnnotations]) => {
  annotations = mergedAnnotations(fileAnnotations);
  records = standardized.markers;
  const originals = new Map(collection.markers.map(marker => [marker.id, marker.file]));
  svgCache = await Promise.all(records.map(async record => { const annotation = familyAnnotation(record); if (hasAssignments(annotation)) return annotatedSvg(await fetch(`../${originals.get(record.id)}?v=source-safe-1`).then(r => r.text()), annotation); return fetch(`../${record.file}?v=source-safe-1`).then(r => r.text()); }));
  families = buildFamilies();
  document.querySelector('#marker-count').textContent = `${families.length} designs · ${records.length} weights`;
  const gallery = document.querySelector('#gallery');
  families.forEach((family, index) => { const button = document.createElement('button'); button.className = 'marker-card'; button.dataset.family = index; button.dataset.search = `${family.key} ${family.variants.map(variant => variant.record.id).join(' ')}`.toLowerCase(); button.setAttribute('aria-pressed', 'false'); button.innerHTML = `<span class="thumb">${svgCache[family.cover.index]}</span><small>${family.key}</small><em>${family.variants.length} weight${family.variants.length > 1 ? 's' : ''}</em>`; button.onclick = () => { select(index, family.variants.indexOf(family.cover)); document.querySelector('.workbench').scrollIntoView({block: 'start', behavior: 'smooth'}); }; gallery.append(button); });
  select(0, families[0].variants.indexOf(families[0].cover));
  filterGallery();
});
document.querySelector('#copy').onclick = async () => { await navigator.clipboard.writeText(markerCss(currentVariant().record)); const button = document.querySelector('#copy'); button.textContent = 'Copied'; setTimeout(() => button.textContent = 'Copy CSS', 1200); };
document.querySelector('#reset').onclick = () => { Object.entries(defaultTheme).forEach(([part, value]) => setColor(part, value)); render(); };
document.querySelector('#search').oninput = filterGallery;
